### ISSUE TITLE
gulp-check-deps throws errors in Windows environments

### ISSUE THREAD

**Issue by calvinlfer** [pmsipilot/gulp-check-deps#2]
On Windows 7/10 machines, I get the following error when I run gulp-check-deps as a gulp task. 

![image](https://cloud.githubusercontent.com/assets/14280155/11432433/733c0062-947c-11e5-8d1a-a8d66504bef5.png)

```
$ gulp check-deps
[20:26:31] Using gulpfile D:\Repositories\offer-api\gulpfile.js
[20:26:31] Starting 'check-deps'...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:452:9)
    at process._tickDomainCallback (node.js:407:17)
```

I do not have this problem in UNIX and OS X environments.

**Comment by jubianchi** [comment]
the error may come from npm not being found when trying to run the underlying command.

Did you try to force the `npmPath` in the options ?

**Comment by calvinlfer** [comment]
I'm not sure how to do that, would you be so kind as to give me some more information/point me in the right direction?

**Comment by mitraSal** [comment]
In Windows 7, looking under my users\AppData\Roaming I could see that npm folder exists but I still get this error.

**Comment by jubianchi** [comment]
@referentiallytransparent try this:

``` js
gulp.task('check-deps', function() {
    var checkDepsConfig = {
        npmPath: 'C:\path\to\npm'
    };

    return gulp.src('package.json').pipe(checkDeps(checkDepsConfig));
});
```

**Comment by mitraSal** [comment]
No, I tried it and it didn't work.

**Comment by jubianchi** [comment]
I'm sorry, I don't have any WIndows box to try to reproduce the bug. 

The more clue you can give me, the better it will be to debug and fix the issue.

**Comment by mitraSal** [comment]
So basically in the command prompt I run the following:
npm
and I can see the following:
npm@2.14.4 C:\Program Files\nodejs\node_modules\npm

So I copied this path and added to the code above in "npmPath" and run gulp on my project and I can still see the same issue as noted above by @referentiallytransparent.

**Comment by jubianchi** [comment]
@mitraSal the path should directly point to the actual npm CLI script so it should look like `C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js`

**Comment by mitraSal** [comment]
Sorry I did as you suggested:
gulp.task('check-deps', function () {
  var checkDepsConfig = {
    npmPath: ' C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'
  };

  return gulp.src('package.json').pipe(checkDeps(checkDepsConfig));
});

and I still got the same error as mentioned above.
Thanks for your help and looking into this.
